name = "ThreeBodyDecay"
uuid = "e6563dab-9ca1-5843-bde3-2ccf38d63843"
authors = ["Misha Mikhasenko <mikhail.mikhasenko@gmail.com>"]
version = "0.6.0"

[deps]
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PartialWaveFunctions = "793d2195-304b-438e-bbb1-bc33c872ac39"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Cuba = "2.0"
Parameters = "0.12.0"
PartialWaveFunctions = "0.2.0"
QuadGK = "2.4.0"
RecipesBase = "1.0.0"
StaticArrays = "1.2.0"
julia = "1.6"

[extras]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "GSL", "Statistics"]
