name = "ThreeBodyDecay"
uuid = "e6563dab-9ca1-5843-bde3-2ccf38d63843"
authors = ["Misha Mikhasenko <mikhail.mikhasenko@gmail.com>"]
version = "0.3.0"

[deps]
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
PartialWaveFunctions = "793d2195-304b-438e-bbb1-bc33c872ac39"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "GSL"]
